In [19]:
import pandas as pd
# import matplotlib.pyplot as plt
import numpy as np
# # import random

In [68]:
# fig, plot_objects = plt.subplots(nrows =2 , ncols =2, figsize = (12, 4))

In [69]:
# plot_objects[0,0].plot(np.random.randn(50), c= 'red')
# fig

In [20]:
# url = 'https://en.wikipedia.org/wiki/The_Simpsons'
# # 
# nba_tables = pd.read_html(url)
# nba_tables[1].head(25)

In [79]:
a = np.random.randint(10, size= 4)
b = np.random.randint(10, size = (4, 3, 2))
print(a)
print('---'*15)
print(b)
# print(np.hstack((a, b)))

[9 4 0 6]
---------------------------------------------
[[[3 3]
  [6 6]
  [6 1]]

 [[5 0]
  [0 6]
  [2 0]]

 [[3 1]
  [1 2]
  [4 9]]

 [[5 4]
  [4 3]
  [5 7]]]


In [83]:
d = np.array([[1,2],[2,3],[3,4]])
e = np.array([[3,4],[13,5],[19,6]])
f = np.hstack((d,e))
print(d)
print('---'*15)
print(f)
print('--'*15)
print(f.shape)


[[1 2]
 [2 3]
 [3 4]]
---------------------------------------------
[[ 1  2  3  4]
 [ 2  3 13  5]
 [ 3  4 19  6]]
------------------------------
(3, 4)
